---
title: "Storage Configuration"
date: 2018-05-08T08:52:46-07:00
draft: false
weight: 3
---

:toc:
Latest Release: 2.2.0 {docdate}

== Available Storage Types

The Container Suite is tested on 3 different storage backends:

 * hostPath (single node testing)
 * NFS (single and multi-node testing)
 * Gluster (dynamic storage on separate Gluster cluster)

Other storage backends work as well including GCE, EBS, ScaleIO, and
others, but may require you to modify various examples or configuration.

Crunchy Containers are tested, developed, and examples provided
that use the various storage types listed above.  This insures
that customers have a high degree of choices when it comes to
choosing a volume type.  HostPath and NFS allow precise host path
choices for where database volumes are persisted.  HostPath and NFS
also allow governance models where volume creation is performed
by an administrator instead of the application/developer team.

Where customers desire a dynamic form of volume creation (e.g. self service),
storage classes are also supported within the example set.

Environment variables are set to determine how and what storage
is to be used.

== HostPath

HostPath is the simplest storage backend to setup. It is only feasible
on a single node but is sufficient for testing the examples.  In your `.bashrc`
file, add the following variables to specify unique settings to
the HostPath directory:
....
export CCP_SECURITY_CONTEXT=""
export CCP_STORAGE_PATH=/data
export CCP_STORAGE_MODE=ReadWriteMany
export CCP_STORAGE_CAPACITY=400M
....

NOTE: It may be necessary to grant your user in OpenShift or Kubernetes the
rights to modify the hostaccess SCC. This can be done with the command: `oadm policy add-scc-to-user hostaccess $(oc whoami)`

{{% notice tip %}}
When running examples against HostPath storage, the run scripts provided in the
examples will create directories using the following pattern:

`$CCP_STORAGE_PATH/$CCP_NAMESPACE-<EXAMPLE_NAME>`
{{% /notice %}}

== NFS

NFS can also be used as a storage mechanism.  Instructions
on setting up NFS are found at the bottom of this guide.

For testing with NFS, in your *.bashrc* file, include
the following variables that are unique to your NFS environment:
....
export CCP_SECURITY_CONTEXT='"supplementalGroups": [65534]'
export CCP_STORAGE_PATH=/nfsfileshare
export CCP_NFS_IP=<IP OF NFS SERVER>
export CCP_STORAGE_MODE=ReadWriteMany
export CCP_STORAGE_CAPACITY=400M
....

In the example above the group ownership of the NFS mount is assumed to be
*nfsnobody* or *65534*.  Additionally, it is recommended that root not be squashed on
the NFS share (`no_root_squash`) in order to ensure the proper directories can be
created, modified and removed as needed for the various container examples.

{{% notice warning %}}
The examples in the Crunchy Container suite need access to the NFS export to create
the directories used by the examples.  The NFS export should be mounted locally so
the example `run.sh` scripts can do proper setup.
{{% /notice %}}

{{% notice tip %}}
NWhen running examples against NFS storage, the run scripts provided in the
examples will create directories using the following pattern:

`$CCP_STORAGE_PATH/$CCP_NAMESPACE-<EXAMPLE_NAME>`
{{% /notice %}}

{{%expand "Configuration Notes for NFS" %}}

Note: Most of the Crunchy containers run as the postgres UID (26), but you
will notice that when `supplementalGroups` is specified, the pod
will include the `nfsnobody` group in the list of groups for the pod user.

First, if you are running your NFS system with SELinux in enforcing mode, you will need to run the following command to allow NFS write permissions:
....
sudo setsebool -P virt_use_nfs 1
....

Detailed instructions that you can use for setting up a NFS server on Centos 7 are provided in the following link.

http://www.itzgeek.com/how-tos/linux/centos-how-tos/how-to-setup-nfs-server-on-centos-7-rhel-7-fedora-22.html

If you are running your client on a VM, you will need to
add 'insecure' to the exportfs file on the NFS server due to the way port
translation is done between the VM host and the VM instance.

For more details on this bug, please see the following link.

http://serverfault.com/questions/107546/mount-nfs-access-denied-by-server-while-mounting

A suggested best practice for tuning NFS for PostgreSQL is to configure the PostgreSQL fstab
mount options like so:

....
proto=tcp,suid,rw,vers=3,proto=tcp,timeo=600,retrans=2,hard,fg,rsize=8192,wsize=8192
....

Network options:
....
MTU=9000
....

If interested in mounting the same NFS share multiple times on the same mount point,
look into the link:https://www.novell.com/support/kb/doc.php?id=7010210[noac mount option].

{{% /expand%}}

== Dynamic Storage

Dynamic storage classes can be used for the examples.  There
are various providers and solutions for dynamic storage, see the Kubernetes
documentation on supported storage choices.
The environment variable `CCP_STORAGE_CLASS` is used
in the examples to determine whether or not to create a PersistentVolume
manually or that it will be created dynamically using a StorageClass.  In
the case of GKE, the default StorageClass is named *default*.   Storage
class names are determined by the Kubernetes administrator and can vary.

Using block storage requires a security context to be set
as follows:
....
export CCP_SECURITY_CONTEXT='"fsGroup":26'
export CCP_STORAGE_CLASS=standard
export CCP_STORAGE_MODE=ReadWriteOnce
export CCP_STORAGE_CAPACITY=400M
....

== Next Steps

There are many ways to configure the examples and containers further. Descriptions of each container
offered and the variables that can be used to customize them are found on the
link:/container-specifications/[Container Specifications] page.

Information can be found on the full scope of examples that can be performed on the
link:/getting-started/[Getting Started] page.
