.TH "pgbasebackup-restore" "1" " Container Image Pages" "Crunchy Data" "2019"
.nh
.ad l


.SH NAME
.PP
Crunchy pgbasebackup\-restore \- provides the ability to restore a database using a pg_basebackup backup\&.


.SH DESCRIPTION
.PP
The Crunchy pgbasebackup\-restore container restores a database into a specified PGDATA directory using a pg_basebackup 
backup, while also preparing for a PITR if a recovery target is specified\&.

.PP
The container itself consists of:
    \- RHEL7 base image
    \- bash script that performs the container startup
    \- rsync to restore the pg_basebackup backup

.PP
Files added to the container during docker build include: /help.1.


.SH USAGE
.PP
See the crunchy docs.

.PP
\fB\fCVersion=\fR

.PP
The Red Hat Enterprise Linux version from which the container was built. For example, Version="7.7"

.PP
\fB\fCRelease=\fR

.PP
The specific release number of the container. For example, Release="4.1.2"
