= Gluster Setup

== Gluster Host Setup

for this test, I installed gluster on a centos
host, I then connect to it from the RHEL ose host.

Here is the how-to that I followed when
installing gluster on the centos host:

https://wiki.centos.org/HowTos/GlusterFSonCentOS
https://wiki.centos.org/SpecialInterestGroup/Storage/gluster-Quickstart

here is the list of commands on the centos box:

....
wget -P /etc/yum.repos.d/ http://download.gluster.org/pub/gluster/glusterfs/LATEST/CentOS/glusterfs-epel.repo
yum install glusterfs-server samba -y
pvcreate /dev/vdb
vgcreate vg_gluster /dev/vdb
lvcreate -L 1G -n brick1 vg_gluster
mkfs.xfs /dev/vg_gluster/brick1
mkdir -p /bricks/brick{1,2}
mount /dev/vg_gluster/brick1 /bricks/brick1
vi /etc/fstab
systemctl enable glusterd.service
systemctl start glusterd.service
gluster peer status
mkdir /bricks/brick1/brick
gluster volume info all
yum install glusterfs glusterfs-fuse attr -y
cat /etc/fstab
gluster peer probe
gluster peer probe centos.crunchy.lab
gluster peer status
gluster volume create glustervol1 transport tcp 192.168.0.108:/bricks/brick1/brick
gluster volume start glustervol1
gluster volume info all
mount -f glusterfs 192.168.0.108:/glustervol1 /mnt/
mount -t glusterfs 192.168.0.108:/glustervol1 /mnt/
ls /mnt/
touch /bricks/brick1/brick/fooberry
cd /bricks/brick1/brick/
chmod 777 brick
....

== OSE Host Setup

on the RHEL ose host, I installed the following:

....
yum -y install glusterfs glusterfs-fuse
mkdir /mnt/gluster
mount -f glusterfs 192.168.0.108:/glustervol1 /mnt/gluster/
....
