.TH "restore " "1" " Container Image Pages" "Crunchy Data" "March 2018"
.nh
.ad l


.SH NAME
.PP
restore \- restore container image


.SH DESCRIPTION
.PP
The restore image provides a means of performing a restore of a dump from pg_dump or pg_dumpall via psql or pg_restore to a Postgres container database.

.PP
The container itself consists of:
    \- RHEL7 base image
    \- bash script that performs the container startup
    \- Postgres binary packages

.PP
Files added to the container during docker build include: /help.1.


.SH USAGE
.PP
See the crunchy docs.


.SH LABELS
.PP
The starter container includes the following LABEL settings:

.PP
That atomic command runs the docker command set in this label:

.PP
\fB\fCName=\fR

.PP
The registry location and name of the image. For example, Name="crunchydata/restore".

.PP
\fB\fCVersion=\fR

.PP
The Red Hat Enterprise Linux version from which the container was built. For example, Version="7.3".

.PP
\fB\fCRelease=\fR

.PP
The specific release number of the container. For example, Release="2.0"
