[[constraint]]
  name = "github.com/fatih/color"
  version = "1.9.0"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.3.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.6"

[[constraint]]
  name = "gopkg.in/ory-am/dockertest.v3"
  version = "3.4.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "12.0.0"

[prune]
  go-tests = true
  unused-packages = true
