FROM registry.access.redhat.com/rhel
MAINTAINER Crunchy Data <support@crunchydata.com>

LABEL Release="0.0.1" Vendor="Crunchy Data Solutions"

ADD bin/crunchy-sim /usr/bin

VOLUME /config

USER daemon

CMD ["crunchy-sim", "--config=/config/config/yaml", "queries.yaml"]
