#!/bin/bash
export PGPASSFILE=/tmp/testing-pgpass
chmod 700 $PGPASSFILE
/bin/rm $PGPASSFILE

echo "creating PGPASSFILE..."
echo "*:*:*:*:password" > $PGPASSFILE
chmod 400 $PGPASSFILE

echo CCPROOT is $CCPROOT

