= Crunchy Openshift Templates - Small-Medium-Large Profiles

== Purpose

The templates-sml directory has 3 different *profiles* of
PostgreSQL deployment configurations.  These templates are
representative of what can be built for a typical user
wanting to implement a *self-service* database-as-a-service.

The templates were tested on Openshift 3.6 and Gluster Container
Native storage.

=== crunchy-small-config

The *small* configuration is a simple Primary Deployment
and related Service.  The example specifies a storage class to
be used (e.g. Gluster Container Native Storage).  There are
also CPU and Memory limits placed in the containers.

=== crunchy-medium-config

The *medium* configuration is a more advanced version of
the *small* template with the addition of a single async replica
that can act as a backup to the primary in the event of a failure.

There are no memory and CPU limits set for this template.

crunchy-collect has been added into the primary database pod to
collect metrics.

The replica is run as a simple Pod but persists data to the
same storage class as the primary.

There is only a single Primary Service created so access to the
replica is limited, the replica only serves as a backup to the
primary.

=== crunchy-large-config

The *large* configuration is an advanced configuration
that would simulate a postgres HA environment.

The primary has a Service and also the replica(s) have a Service
so applications can access both.

The primary is run in a Deployment which lets Openshift relocate
the Deployment if a node fails for any reason.

Pgpool is also deployed which allows applications to have a
SQL routing capability in front of their postgres cluster. Pgpool is
also run in a Deployment which allows for HA of pgpool.

There are no CPU or memory limits set for either primary or replicas.

The replica(s) are run withing a StatefulSet and use dynamic storage
provisioning.  You can therefore scale up the number of replicas
as you require after the initial cluster deployment.


=== pgweb

The *pgweb* template runs a simple web application you can use to demonstrate
how an application can be bound to a postgres cluster.

=== metrics

The *metrics* template allows you to deploy the entire Crunchy metrics
containers using an Openshift template.  It is useful to show metrics
flowing from the Small/Medium/Large deployments to the Metrics backends.

The example also shows how to specify dynamic storage for the
metrics persistence.

=== backup

The *backup* template shows how dynamic storage can be used to perform
a backup of a database.
