.TH "collect " "1" " Container Image Pages" "Jeff McCormick" "April 13, 2017"
.nh
.ad l


.SH NAME
.PP
collect \- collect container image


.SH DESCRIPTION
.PP
PostgreSQL metrics collection container. Every 5 seconds the collection container will collect PostgreSQL metrics which can be scrapped by Crunchy Prometheus container. These can be graphed using the Crunchy Grafana container.

.PP
The container itself consists of:
    \- RHEL7 base image
    \- Node Exporter
    \- PostgreSQL Exporter
    \- bash script that performs the container startup
    \- PostgreSQL binary packages

.PP
Files added to the container during docker build include: /help.1.


.SH USAGE
.PP
See the crunchy docs.


.SH LABELS
.PP
The starter container includes the following LABEL settings:

.PP
That atomic command runs the docker command set in this label:

.PP
\fB\fCName=\fR

.PP
The registry location and name of the image. For example, Name="crunchydata/collect".

.PP
\fB\fCVersion=\fR

.PP
The Red Hat Enterprise Linux version from which the container was built. For example, Version="7.3".

.PP
\fB\fCRelease=\fR

.PP
The specific release number of the container. For example, Release="2.0"
