Name: crunchy-basic
PrimaryName: crunchy-basic
PrimaryPassword: password
RootPassword: password
UserPassword: password
ServiceType: ClusterIP
ContainerName: server
PostgresImage: crunchydata/crunchy-postgres:centos7-9.6.5-1.6.0
NFSServerIP: 10.0.1.4
NFSPath: /mnt/nfsfileshare
PVStorage: 400M
PVName: crunchy-basic-pv
PVCName: crunchy-basic-pvc
