name: basic
container:
  port: 5432
  name: basic
credentials:
  primary: password
  root: password
  user: password
serviceType: ClusterIP
image:
  repository: crunchydata
  container: crunchy-postgres
  tag: centos7-9.6.8-1.8.2
resources:
  cpu: 200m
  memory: 512Mi
