FROM centos:7

LABEL Release="1.3" Vendor="Crunchy Data Solutions"

RUN yum -y install procps-ng iproute bind-utils openssh-clients hostname  && yum clean all -y

# set up cpm directory
#
RUN mkdir -p /opt/cpm/bin

ADD bin/vacuum /opt/cpm/bin

USER root

CMD ["/opt/cpm/bin/start-vacuum.sh"]

