ARG BASEOS
ARG RELVER
FROM centos:${BASEOS}

LABEL vendor="Crunchy Data" \
	url="https://crunchydata.com" \
	release="${RELVER}" \
	org.opencontainers.image.vendor="Crunchy Data" \
	os.version="7.7"

COPY licenses /licenses

ENV LC_ALL en_US.utf-8
ENV LANG en_US.utf-8

RUN yum -y update \
	&& yum -y install \
		--setopt=skip_missing_names_on_install=False \
		bind-utils \
		epel-release \
		gettext \
		hostname \
		procps-ng \
	&& yum -y clean all
