FROM centos:7

LABEL Release="1.3" Vendor="Crunchy Data Solutions"

#RUN rpm -Uvh http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum -y install procps-ng iproute bind-utils openssh-clients hostname  && yum clean all -y

# set up cpm directory
#
RUN mkdir -p /opt/cpm/bin

ADD bin/dns /opt/cpm/bin

USER root

# expose the consul port used for DNS
EXPOSE 8500
EXPOSE 8600

VOLUME ["consuldata"]

CMD ["/opt/cpm/bin/start-dnsbridge.sh"]

