ARG RELVER
FROM centos:7

LABEL vendor="Crunchy Data" \
	Version="7.7" \
	Release="${RELVER}" \
	url="https://crunchydata.com" \
	org.opencontainers.image.vendor="Crunchy Data" \
	os.version="7.7"

COPY licenses /licenses

RUN yum -y update \
	&& yum -y install \
		--setopt=skip_missing_names_on_install=False \
		bind-utils \
		epel-release \
		gettext \
		hostname \
		procps-ng \
	&& yum -y clean all
