FROM centos:7

LABEL  Vendor="Crunchy Data Solutions" \
        Release="2.0"

ADD bin/crunchy-sim /usr/bin
ADD bin/common /opt/cpm/bin

VOLUME /config

USER daemon

CMD ["crunchy-sim", "--config=/config/config/yaml", "queries.yaml"]
