= Smoke Test Guide - Crunchy Containers for PostgreSQL
Crunchy Data Solutions, Inc.
:toc:
v1.5, {docdate}

== Prerequsites

You will need to do the following steps prior to testing.

*Note*: If version numbers have not been updated, you will need update version numbers in documentation and examples in your test instance.

It is recommended to build a clean virtual machine for all three applications (Docker, OpenShift, Kubernetes) on both operating systems (CentOS 7, RHEL 7). This will ensure the most accurate results from testing.

 * Build a clean Docker CentOS 7 host (VM)
 * Build a clean OpenShift CentOS 7 host (VM)
 * Build a clean Kubernetes CentOS 7 host (VM)
 * Build a clean Docker RHEL 7 host (VM)
 * Build a clean OpenShift RHEL 7 host (VM)
 * Build a clean Kubernetes RHEL 7 host (VM)

At this point, you can build the 9.5 and 9.6 images on all three hosts. (Or if you're testing a new PostgreSQL release, you can build those at this point also.)

 * Build the 9.5 and 9.6 images on the new Docker host
 * Build the 9.5 and 9.6 images on the new OpenShift host
 * Build the 9.5 and 9.6 images on the new Kubernetes host

== New Container Release Testing

The following examples are used to test each environment:

 * basic
 * backup
 * restore
 * grafana/prometheus/promgateway
 * collect example
 * master-replica
 * pgpool
 * pgbouncer
 * crunchy-proxy
 * sync example

 == New PostgreSQL Release Testing

 The following examples are used to test each environment:

 * basic
 * backup
 * restore
 * grafana/prometheus/promgateway
 * collect example
 * master-replica
 * pgpool
 * pgbouncer
 * crunchy-proxy
 * sync example


== Legal Notices

Copyright © 2017 Crunchy Data Solutions, Inc.

CRUNCHY DATA SOLUTIONS, INC. PROVIDES THIS GUIDE "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.

Crunchy, Crunchy Data Solutions, Inc. and the Crunchy Hippo Logo are trademarks of Crunchy Data Solutions, Inc.
