name: Trivy PR Scan

on:
  pull_request:
    branches:
      - REL_4_7
  push:
    branches:
      - REL_4_7
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log actionable vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          hide-progress: true
          ignore-unfixed: true
          exit-code: 1
